# Core Settings
HOSTNAME=mail.nof.internal
FIRST_MAIL_DOMAIN=nof.internal
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=Happy1234!

# Backend choice
USE_LDAP=1
USE_POSTGRESQL=0
USE_MYSQL=1 # Required for Roundcube/iRedAdmin even with LDAP