HOSTNAME=mail.nof.internal
FIRST_MAIL_DOMAIN=nof.internal
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=Happy1234!
USE_LDAP=1
USE_POSTGRESQL=0
USE_MYSQL=1
CHECK_QUOTA=NO
USE_CLAMAV=NO
USE_SPAMASSASSIN=NO
HTTPS=no
# ADDED: Explicitly disable heavy initialization checks
ACL_BACKEND=ldap
CLAMAV_STAMPD=NO
MLMMJADMIN_STAMPD=NO